name: dp_uied3
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.11
  - aom=3.7.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.2.0
  - blas=1.0
  - blinker=1.7.0
  - bottleneck=1.3.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.3.11
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - cairo=1.18.0
  - catalogue=2.0.10
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - confection=0.1.4
  - contourpy=1.1.1
  - cryptography=41.0.3
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cycler=0.12.1
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dav1d=1.2.1
  - dbus=1.13.6
  - double-conversion=3.3.0
  - expat=2.6.2
  - ffmpeg=6.1.1
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - gast=0.5.4
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib=2.80.0
  - glib-tools=2.80.0
  - gmp=6.3.0
  - gnutls=3.7.9
  - google-auth=2.29.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.54.3
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h5py=3.11.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.4
  - imath=3.1.11
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_resources=6.4.0
  - jasper=4.2.3
  - jinja2=3.1.3
  - joblib=1.2.0
  - keras=2.13.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang-cpp18.1=18.1.3
  - libclang13=18.1.3
  - libcups=2.3.3
  - libcurl=8.7.1
  - libdeflate=1.20
  - libdrm=2.4.120
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libglu=9.0.0
  - libgomp=13.2.0
  - libgpg-error=1.48
  - libgrpc=1.54.3
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libllvm18=18.1.3
  - libnghttp2=1.58.0
  - libogg=1.3.4
  - libopenblas=0.3.27
  - libopencv=4.9.0
  - libopenvino=2023.2.0
  - libopenvino-auto-batch-plugin=2023.2.0
  - libopenvino-auto-plugin=2023.2.0
  - libopenvino-hetero-plugin=2023.2.0
  - libopenvino-intel-cpu-plugin=2023.2.0
  - libopenvino-intel-gpu-plugin=2023.2.0
  - libopenvino-ir-frontend=2023.2.0
  - libopenvino-onnx-frontend=2023.2.0
  - libopenvino-paddle-frontend=2023.2.0
  - libopenvino-pytorch-frontend=2023.2.0
  - libopenvino-tensorflow-frontend=2023.2.0
  - libopenvino-tensorflow-lite-frontend=2023.2.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.21.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxkbcommon=1.7.0
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - mdurl=0.1.2
  - mpg123=1.32.6
  - multidict=6.0.5
  - munkres=1.1.4
  - murmurhash=1.0.10
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nccl=2.21.5.1
  - ncurses=6.4
  - nettle=3.9.1
  - nspr=4.35
  - nss=3.98
  - numexpr=2.8.4
  - numpy=1.24.4
  - oauthlib=3.2.2
  - ocl-icd=2.3.2
  - ocl-icd-system=1.0.0
  - opencv=4.9.0
  - openexr=3.2.2
  - openh264=2.4.0
  - openjpeg=2.5.2
  - openssl=3.2.1
  - opt_einsum=3.3.0
  - p11-kit=0.24.1
  - packaging=24.0
  - pandas=2.0.3
  - pathy=0.10.3
  - pcre2=10.43
  - pillow=10.3.0
  - pip=23.3.1
  - pixman=0.43.2
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - preshed=3.0.9
  - protobuf=4.21.12
  - pthread-stubs=0.4
  - pugixml=1.14
  - pulseaudio-client=17.0
  - py-opencv=4.9.0
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.21
  - pydantic=1.10.14
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.8.2
  - python-flatbuffers=24.3.25
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - qt-main=5.15.8
  - qt6-main=6.6.3
  - re2=2023.03.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=2.0.0
  - rich=13.7.1
  - rsa=4.9
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=68.2.2
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - smart_open=6.4.0
  - snappy=1.1.10
  - spacy=3.7.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.41.2
  - srsly=2.4.8
  - svt-av1=1.8.0
  - tbb=2021.12.0
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.13.1
  - tensorflow-base=2.13.1
  - tensorflow-estimator=2.13.1
  - termcolor=2.4.0
  - thinc=8.2.2
  - threadpoolctl=2.2.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4
  - tqdm=4.66.2
  - typer=0.9.4
  - unicodedata2=15.1.0
  - urllib3=1.26.18
  - wasabi=1.1.2
  - weasel=0.3.4
  - werkzeug=3.0.2
  - wheel=0.41.2
  - wrapt=1.16.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.41
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yarl=1.9.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - en-core-web-trf==3.7.3
      - filelock==3.13.4
      - fsspec==2024.3.1
      - mpmath==1.3.0
      - networkx==3.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - regex==2024.4.16
      - spacy-curated-transformers==0.2.2
      - sympy==1.12
      - torch==2.2.2
      - triton==2.2.0
      - typing-extensions==4.11.0
prefix: /root/miniconda3/envs/dp_uied3
